version: "3"
services:
        web:
                build: .
                ports:
                        - "8999:80"
                volumes:
                        - "./app:/var/www/html"
                restart: always

